import {useCallback,useEffect,useMemo,useState} from 'react';
import {Alert,Button,Checkbox,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {apiPost} from '../../api/apiPost';
import fetchClient from '../../utils/fetchClient';
import {loadErrorMessage} from '../../utils/loadErrorMessage';

type EntityType='PROVIDER_PROFILE'|'PUBLIC_METADATA'|'RETENTION_PROFILE'|'SIGNING_PROFILE'|'SIGNING_KEY'|'SKILL_ALIAS'|'EXTENSION'|'BACKEND_TRANSPORT_PROFILE'|'EXTENDED_CARD_PROFILE'|'PUSH_PROFILE'|'CALLBACK_REGISTRATION';
type Entity={entityType:EntityType;entityKey:string;values:Record<string,unknown>;aggregateVersion:number};
type Field={key:string;label:string;kind?:'number'|'boolean'|'json'|'select'|'relation'|'multi-relation';options?:string[];relationType?:EntityType|'AGENT'|'SKILL';required?:boolean};
type Choice={value:string;label:string};
const TYPES:Record<EntityType,{label:string;fields:Field[];defaults:Record<string,unknown>}>= {
  PROVIDER_PROFILE:{label:'Provider profiles',defaults:{},fields:[{key:'profileName',label:'Profile name',required:true},{key:'providerName',label:'Provider name',required:true},{key:'providerUrl',label:'Provider HTTPS URL'},{key:'documentationUrl',label:'Documentation HTTPS URL'},{key:'iconUrl',label:'Icon HTTPS URL'}]},
  PUBLIC_METADATA:{label:'Agent public metadata',defaults:{sourceProvenance:{}},fields:[{key:'agentDefId',label:'Agent definition',kind:'relation',relationType:'AGENT',required:true},{key:'providerProfileId',label:'Provider profile',kind:'relation',relationType:'PROVIDER_PROFILE'},{key:'displayName',label:'Public display name'},{key:'description',label:'Public description'},{key:'documentationUrl',label:'Documentation HTTPS URL'},{key:'iconUrl',label:'Icon HTTPS URL'},{key:'semanticVersion',label:'Semantic version'},{key:'sourceProvenance',label:'Source provenance',kind:'json'}]},
  RETENTION_PROFILE:{label:'Artifact retention profiles',defaults:{taskRetentionDays:30,artifactRetentionDays:30,maximumArtifactBytes:10485760},fields:[{key:'profileName',label:'Profile name',required:true},{key:'taskRetentionDays',label:'Task retention days',kind:'number',required:true},{key:'artifactRetentionDays',label:'Artifact retention days',kind:'number',required:true},{key:'maximumArtifactBytes',label:'Maximum artifact bytes',kind:'number',required:true},{key:'accessPolicyRef',label:'Existing access-control policy reference',required:true}]},
  SIGNING_PROFILE:{label:'Signing profiles',defaults:{purpose:'A2A_CARD_NATIVE',algorithm:'RS256',rotationPolicy:{},revocationEpoch:0,isDefault:false},fields:[{key:'environment',label:'Environment',required:true},{key:'profileName',label:'Profile name',required:true},{key:'purpose',label:'Purpose',kind:'select',options:['A2A_CARD_NATIVE','A2A_CARD_EXTERNAL_FACADE'],required:true},{key:'algorithm',label:'Algorithm',kind:'select',options:['RS256'],required:true},{key:'jwksUrl',label:'Public JWKS HTTPS URL',required:true},{key:'managedKeyAlias',label:'Managed key alias',required:true},{key:'rotationPolicy',label:'Rotation policy',kind:'json'},{key:'revocationEpoch',label:'Revocation epoch',kind:'number'},{key:'isDefault',label:'Default for purpose',kind:'boolean'}]},
  SIGNING_KEY:{label:'Signing key lifecycle',defaults:{publicJwk:{},keyState:'CURRENT'},fields:[{key:'signingProfileId',label:'Signing profile',kind:'relation',relationType:'SIGNING_PROFILE',required:true},{key:'kid',label:'Key ID',required:true},{key:'publicJwk',label:'Public RSA JWK',kind:'json',required:true},{key:'managedKeyAlias',label:'Managed key alias',required:true},{key:'keyState',label:'State',kind:'select',options:['CURRENT','PREVIOUS','REVOKED'],required:true},{key:'validFrom',label:'Valid from (RFC 3339)',required:true},{key:'validUntil',label:'Valid until (RFC 3339)'}]},
  SKILL_ALIAS:{label:'Public skill aliases',defaults:{},fields:[{key:'publicationAlias',label:'Stable public alias',required:true},{key:'skillId',label:'Internal skill',kind:'relation',relationType:'SKILL',required:true},{key:'skillVersion',label:'Pinned Skill version',required:true},{key:'skillDigest',label:'Pinned sha256 digest',required:true}]},
  EXTENSION:{label:'Extension registry',defaults:{schemaDocument:{},dependencyIds:[],activationState:'DRAFT'},fields:[{key:'extensionUri',label:'Extension HTTPS URI',required:true},{key:'extensionVersion',label:'Extension version',required:true},{key:'description',label:'Description'},{key:'schemaDocument',label:'Schema document',kind:'json'},{key:'dependencyIds',label:'Extension dependencies',kind:'multi-relation',relationType:'EXTENSION'},{key:'activationState',label:'Activation state',kind:'select',options:['DRAFT','OPTIONAL_DATA','DISABLED'],required:true}]},
  EXTENDED_CARD_PROFILE:{label:'Extended Agent Card profiles',defaults:{allowedPrincipalPrefixes:[],cardDocument:{},profileState:'APPROVED'},fields:[{key:'profileName',label:'Profile name',required:true},{key:'authorizationPolicyDigest',label:'Authorization policy sha256 digest',required:true},{key:'allowedPrincipalPrefixes',label:'Allowed principal prefixes',kind:'json',required:true},{key:'cardDocument',label:'Unsigned extended Agent Card document',kind:'json',required:true},{key:'profileState',label:'State',kind:'select',options:['APPROVED','DISABLED'],required:true}]},
  PUSH_PROFILE:{label:'Push delivery profiles',defaults:{maximumAttempts:5,initialBackoffSeconds:5,maximumBackoffSeconds:300,leaseSeconds:30,requestTimeoutMs:10000,profileState:'APPROVED'},fields:[{key:'environment',label:'Environment',required:true},{key:'profileName',label:'Profile name',required:true},{key:'maximumAttempts',label:'Maximum attempts',kind:'number',required:true},{key:'initialBackoffSeconds',label:'Initial backoff seconds',kind:'number',required:true},{key:'maximumBackoffSeconds',label:'Maximum backoff seconds',kind:'number',required:true},{key:'leaseSeconds',label:'Delivery lease seconds',kind:'number',required:true},{key:'requestTimeoutMs',label:'Request timeout ms (at least 5s below lease)',kind:'number',required:true},{key:'profileState',label:'State',kind:'select',options:['APPROVED','DISABLED'],required:true}]},
  CALLBACK_REGISTRATION:{label:'Approved callback registrations',defaults:{ownerPrincipalPrefixes:[],registrationState:'APPROVED'},fields:[{key:'pushProfileId',label:'Push profile',kind:'relation',relationType:'PUSH_PROFILE',required:true},{key:'registrationName',label:'Registration name',required:true},{key:'callbackUrl',label:'Fixed callback HTTPS URL',required:true},{key:'ownerPrincipalPrefixes',label:'Owner principal prefixes',kind:'json',required:true},{key:'hmacKeyFile',label:'Mounted HMAC key file (/run/secrets/name)',required:true},{key:'registrationState',label:'State',kind:'select',options:['APPROVED','DISABLED'],required:true}]},
  BACKEND_TRANSPORT_PROFILE:{label:'External backend transports',defaults:{contractVersion:'light-a2a-backend/v1',capabilities:{contractVersion:'light-a2a-backend/v1',streaming:true,cancellation:true,statusReconciliation:true,acceptedContentModes:['application/json'],maximumArtifactBytes:10485760},requestTimeoutMs:30000,maximumRequestBytes:1048576,maximumResponseBytes:4194304},fields:[{key:'environment',label:'Environment',required:true},{key:'profileName',label:'Profile name',required:true},{key:'contractVersion',label:'Backend contract',kind:'select',options:['light-a2a-backend/v1'],required:true},{key:'contractDigest',label:'Pinned OpenAPI sha256 digest',required:true},{key:'origin',label:'Fixed loopback origin (http://127.0.0.1:port/)',required:true},{key:'audience',label:'Signed-context audience',required:true},{key:'contextKeyFile',label:'Mounted key file (/run/secrets/name)',required:true},{key:'dataBoundaryDigest',label:'Data-boundary sha256 digest',required:true},{key:'requestTimeoutMs',label:'Request timeout milliseconds',kind:'number',required:true},{key:'maximumRequestBytes',label:'Maximum request bytes',kind:'number',required:true},{key:'maximumResponseBytes',label:'Maximum response bytes',kind:'number',required:true},{key:'capabilities',label:'Declared capabilities',kind:'json',required:true}]},
};
const rpc=(action:string,data:Record<string,unknown>)=>({host:'lightapi.net',service:'genai',action,version:'0.1.0',data});

export default function A2aAuthoringDialog({open,hostId,environment,onClose}:{open:boolean;hostId:string;environment:string;onClose:()=>void}){
  const [rows,setRows]=useState<Entity[]>([]);const [type,setType]=useState<EntityType>('PROVIDER_PROFILE');
  const [editing,setEditing]=useState<Entity|null>(null);const [values,setValues]=useState<Record<string,unknown>>({});
  const [jsonText,setJsonText]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [agents,setAgents]=useState<Choice[]>([]);const [skills,setSkills]=useState<Choice[]>([]);
  const definition=TYPES[type];
  const load=useCallback(async()=>{if(!open||!hostId)return;try{const result=await fetchClient('/portal/query?cmd='+encodeURIComponent(JSON.stringify(rpc('getA2aAuthoring',{hostId,environment}))));setRows(result.a2aAuthoring??[]);setError('');}catch(reason){setError(loadErrorMessage(reason));}},[environment,hostId,open]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!open||!hostId)return;const query=(action:string)=>fetchClient('/portal/query?cmd='+encodeURIComponent(JSON.stringify(rpc(action,{hostId,active:true,offset:0,limit:1000}))));void Promise.all([query('getAgentDefinition'),query('getSkill')]).then(([agentResult,skillResult])=>{setAgents((agentResult.agentDefinitions??agentResult.agents??[]).map((item:Record<string,unknown>)=>({value:String(item.agentDefId),label:String(item.agentName??item.apiName??item.agentDefId)})));setSkills((skillResult.skills??[]).map((item:Record<string,unknown>)=>({value:String(item.skillId),label:String(item.name??item.skillName??item.skillId)})));}).catch(reason=>setError(loadErrorMessage(reason)));},[hostId,open]);
  const visible=useMemo(()=>rows.filter(row=>row.entityType===type),[rows,type]);
  const begin=(row?:Entity)=>{const next=row?{...row.values,...(type==='SIGNING_KEY'?{managedKeyAlias:String(row.values.privateKeyRef??'').replace(/^managed:/,'')}: {})}:{...definition.defaults,...(['SIGNING_PROFILE','BACKEND_TRANSPORT_PROFILE','PUSH_PROFILE'].includes(type)?{environment}:{}),...(type==='SIGNING_KEY'?{validFrom:new Date().toISOString()}: {})};setEditing(row??{entityType:type,entityKey:'',values:next,aggregateVersion:0});setValues(next);setJsonText(Object.fromEntries(definition.fields.filter(field=>field.kind==='json').map(field=>[field.key,JSON.stringify(next[field.key]??(field.key==='dependencyIds'?[]:{}),null,2)])));};
  const save=async()=>{if(!editing)return;setBusy(true);try{const submitted={...values};if(type==='SIGNING_KEY'){submitted.privateKeyRef=`managed:${String(submitted.managedKeyAlias??'')}`;delete submitted.managedKeyAlias;}for(const field of definition.fields.filter(item=>item.kind==='json'))submitted[field.key]=JSON.parse(jsonText[field.key]||'{}');const result=await apiPost({url:'/portal/command',headers:{},body:rpc('putA2aAuthoring',{hostId,entityType:type,...(editing.entityKey?{entityKey:editing.entityKey}:{}),values:submitted,aggregateVersion:editing.aggregateVersion})});if(result.error)throw result.error;setEditing(null);await load();}catch(reason){setError(loadErrorMessage(reason));}finally{setBusy(false);}};
  const remove=async(row:Entity)=>{if(!window.confirm(`Delete ${TYPES[row.entityType].label} entry ${row.entityKey}?`))return;setBusy(true);const result=await apiPost({url:'/portal/command',headers:{},body:rpc('deleteA2aAuthoring',{hostId,entityType:row.entityType,entityKey:row.entityKey,aggregateVersion:row.aggregateVersion})});setBusy(false);if(result.error)setError(loadErrorMessage(result.error));else await load();};
  const update=(field:Field,value:unknown)=>setValues(current=>({...current,[field.key]:value}));
  const choices=(field:Field):Choice[]=>field.relationType==='AGENT'?agents:field.relationType==='SKILL'?skills:rows.filter(row=>row.entityType===field.relationType&&row.entityKey!==editing?.entityKey).map(row=>({value:row.entityKey,label:String(row.values.profileName??row.values.displayName??row.values.extensionUri??row.values.kid??row.entityKey)}));
  return <Dialog open={open} onClose={busy?undefined:onClose} maxWidth="lg" fullWidth><DialogTitle>A2A publication authoring</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>
    <Alert severity="info">These forms update Portal control-plane authoring through CloudEvents. Runtime services see changes only after an explicit signed publication and Config Server snapshot activation.</Alert>{error&&<Alert severity="error">{error}</Alert>}
    <Stack direction="row" spacing={2}><TextField select fullWidth label="Authoring resource" value={type} onChange={event=>{setType(event.target.value as EntityType);setEditing(null);}}>{(Object.keys(TYPES) as EntityType[]).map(key=><MenuItem key={key} value={key}>{TYPES[key].label}</MenuItem>)}</TextField><Button variant="contained" onClick={()=>begin()}>Create</Button></Stack>
    <Paper variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Key</TableCell><TableCell>Summary</TableCell><TableCell>Version</TableCell><TableCell/></TableRow></TableHead><TableBody>{visible.map(row=><TableRow key={row.entityKey}><TableCell>{row.entityKey}</TableCell><TableCell>{String(row.values.profileName??row.values.displayName??row.values.publicationAlias??row.values.kid??row.values.extensionUri??'')}</TableCell><TableCell>{row.aggregateVersion}</TableCell><TableCell><Button size="small" onClick={()=>begin(row)}>Edit</Button><Button size="small" color="error" disabled={Boolean(row.values.frozen)} onClick={()=>void remove(row)}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></Paper>
    {editing&&<Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{mb:2}}>{editing.entityKey?'Edit':'Create'} {definition.label}</Typography><Stack spacing={2}>{definition.fields.map(field=>field.kind==='boolean'?<FormControlLabel key={field.key} control={<Checkbox checked={Boolean(values[field.key])} onChange={event=>update(field,event.target.checked)}/>} label={field.label}/>:field.kind==='select'?<TextField key={field.key} select label={field.label} value={String(values[field.key]??'')} onChange={event=>update(field,event.target.value)}>{field.options?.map(option=><MenuItem key={option} value={option}>{option}</MenuItem>)}</TextField>:field.kind==='relation'||field.kind==='multi-relation'?<TextField key={field.key} select required={field.required} SelectProps={field.kind==='multi-relation'?{multiple:true}:undefined} label={field.label} value={field.kind==='multi-relation'?(values[field.key]??[]):String(values[field.key]??'')} onChange={event=>update(field,event.target.value)}>{!field.required&&field.kind==='relation'&&<MenuItem value="">None</MenuItem>}{choices(field).map(option=><MenuItem key={option.value} value={option.value}>{option.label}</MenuItem>)}</TextField>:field.kind==='json'?<TextField key={field.key} multiline minRows={3} label={field.label} value={jsonText[field.key]??''} onChange={event=>setJsonText(current=>({...current,[field.key]:event.target.value}))}/>:<TextField key={field.key} required={field.required} type={field.kind==='number'?'number':'text'} label={field.label} value={String(values[field.key]??'')} onChange={event=>update(field,field.kind==='number'?Number(event.target.value):event.target.value)}/>)}</Stack><Stack direction="row" spacing={1} justifyContent="flex-end" sx={{mt:2}}><Button onClick={()=>setEditing(null)}>Cancel</Button><Button variant="contained" disabled={busy} onClick={()=>void save()}>Save</Button></Stack></Paper>}
  </Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={busy}>Close</Button></DialogActions></Dialog>;
}
