import type { PageDefinition } from "./types";
import forms from "../data/Forms.json";

export const pageRegistry: PageDefinition[] = [
  {
    id: "task-center",
    title: "Task Center",
    description: "Start from a task and continue across related pages and forms.",
    route: "/app/tasks",
    category: "Tasks",
    kind: "Page",
    helpPath: "/help/portal-view/pages/task-center",
    keywords: ["task", "center", "workflow", "search", "recent", "suggested"],
  },
  {
    id: "mcp-gateway",
    title: "MCP Gateway",
    description: "View onboarded MCP servers, gateway instances, and selected tools.",
    route: "/app/mcp/gateway",
    category: "MCP Gateway",
    roles: ["user"],
    keywords: ["mcp", "gateway", "tool", "server", "onboard"],
    entities: ["api", "apiVersion", "instanceApi"],
  },
  {
    id: "mcp-setup",
    title: "MCP Gateway Setup",
    description: "Task-based MCP onboarding for APIs and standalone MCP servers.",
    route: "/app/mcp/setup",
    category: "MCP Gateway",
    roles: ["user"],
    keywords: ["mcp", "setup", "onboard", "gateway", "task", "server", "tools"],
    entities: ["api", "apiVersion", "instanceApi"],
  },
  {
    id: "mcp-wizard",
    title: "MCP Onboarding Wizard",
    description: "Configure API or standalone MCP server onboarding.",
    route: "/app/mcp/wizard",
    category: "MCP Gateway",
    roles: ["user"],
    keywords: ["mcp", "wizard", "onboard", "server", "tools"],
    entities: ["api", "apiVersion", "instance"],
  },
  {
    id: "api-marketplace",
    title: "API Catalog",
    description: "Browse registered APIs by category, tag, lifecycle status, and owner context.",
    route: "/app/marketplace/api",
    category: "API Marketplace",
    helpPath: "/help/portal-view/pages/api-catalog",
    keywords: ["api", "marketplace", "service", "catalog", "category", "tag", "version", "endpoint", "runtime", "access"],
    entities: ["api"],
  },
  {
    id: "workflow-marketplace",
    title: "Workflow Catalog",
    description: "Browse workflow definitions by taxonomy and start visible workflows.",
    route: "/app/marketplace/workflow",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/pages/workflow-catalog",
    keywords: ["workflow", "marketplace", "catalog", "definition", "start", "process", "task"],
    entities: ["wfDefId"],
  },
  {
    id: "schema-marketplace",
    title: "Schema Catalog",
    description: "Browse JSON schemas by category, tag, status, and external alias.",
    route: "/app/marketplace/schema",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/pages/schema-catalog",
    keywords: ["schema", "json", "marketplace", "catalog", "category", "tag", "alias"],
    entities: ["schema"],
  },
  {
    id: "create-api",
    title: "Create API",
    description: "Register a new API using the service creation form.",
    route: "/app/form/createApi",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/forms/create-api",
    keywords: ["create", "api", "service", "publish"],
    entities: ["api"],
  },
  {
    id: "create-api-version",
    title: "Create API Version",
    description: "Add a new version to an existing API.",
    route: "/app/form/createApiVersion",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/forms/create-api-version",
    keywords: ["api", "version", "create", "service"],
    entities: ["api", "apiVersion"],
  },
  {
    id: "api-admin",
    title: "API Admin",
    description: "Create and manage logical API records.",
    route: "/app/service/admin",
    category: "API Marketplace",
    roles: ["user", "api-admin"],
    helpPath: "/help/portal-view/pages/api-admin",
    keywords: ["api", "admin", "service", "owner"],
    entities: ["api"],
  },
  {
    id: "api-detail",
    title: "API Versions",
    description: "Create and manage versions for a selected API.",
    route: "/app/apiDetail",
    category: "API Marketplace",
    roles: ["user", "api-admin"],
    helpPath: "/help/portal-view/pages/api-detail",
    keywords: ["api", "version", "detail", "service"],
    entities: ["api", "apiVersion"],
  },
  {
    id: "instance-api-mcp-tool",
    title: "Instance API MCP Tools",
    description: "Configure MCP tools exposed for an instance API.",
    route: "/app/instance/InstanceApiMcpTool",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["instance", "mcp", "tool", "configuration"],
    entities: ["instanceApi", "apiVersion"],
  },
  {
    id: "instance-api",
    title: "Instance API",
    description: "Link API versions to runtime or gateway instances.",
    route: "/app/instance/InstanceApi",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/pages/instance-api",
    keywords: ["instance", "api", "gateway", "deploy", "link"],
    entities: ["instance", "apiVersion"],
  },
  {
    id: "instance-admin",
    title: "Instance Admin",
    description: "Create and manage logical service and gateway instances.",
    route: "/app/instance/InstanceAdmin",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/pages/instance-admin",
    keywords: ["instance", "gateway", "runtime", "admin"],
    entities: ["instance"],
  },
  {
    id: "runtime-instance-admin",
    title: "Runtime Instances",
    description: "Create and manage runtime endpoint records.",
    route: "/app/instance/RuntimeInstanceAdmin",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/pages/runtime-instance",
    keywords: ["runtime", "instance", "endpoint", "admin"],
    entities: ["runtimeInstance", "instance"],
  },
  {
    id: "instance-app",
    title: "Instance Apps",
    description: "Link client apps to instances.",
    route: "/app/instance/InstanceApp",
    category: "Platform Operations",
    roles: ["user", "instance-admin", "app-admin"],
    helpPath: "/help/portal-view/pages/instance-app",
    keywords: ["instance", "app", "link"],
    entities: ["instance", "appId"],
  },
  {
    id: "instance-app-api",
    title: "Instance App APIs",
    description: "Link instance app records to instance API records.",
    route: "/app/instance/InstanceAppApi",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/pages/instance-app-api",
    keywords: ["instance", "app", "api", "association"],
    entities: ["instanceApp", "instanceApi"],
  },
  {
    id: "instance-api-path-prefix",
    title: "Instance API Path Prefixes",
    description: "Manage path prefixes for an instance API.",
    route: "/app/instance/InstanceApiPathPrefix",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/pages/instance-api-path-prefix",
    keywords: ["instance", "api", "path", "prefix"],
    entities: ["instanceApi", "pathPrefix"],
  },
  {
    id: "role-admin",
    title: "Role Admin",
    description: "Manage roles used for access control.",
    route: "/app/access/roleAdmin",
    category: "Access Control",
    roles: ["access-admin"],
    keywords: ["role", "access", "permission", "rbac"],
    entities: ["role"],
  },
  {
    id: "access-admin",
    title: "Access Admin",
    description: "Manage portal handler access policies and access control entities.",
    route: "/app/access/admin",
    category: "Access Control",
    roles: ["access-admin"],
    keywords: ["access", "permission", "handler", "endpoint", "role", "group", "attribute", "position"],
    entities: ["role", "group", "attribute", "position", "endpointId", "apiVersionId"],
  },
  {
    id: "config-promotion-export",
    title: "Promotion Export",
    description: "Export configuration promotion data.",
    route: "/app/promotion/export",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["promotion", "export", "configuration", "diff"],
    entities: ["promotion"],
  },
  {
    id: "config-promotion-import",
    title: "Promotion Import",
    description: "Import configuration promotion data.",
    route: "/app/promotion/import",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["promotion", "import", "configuration"],
    entities: ["promotion"],
  },
  {
    id: "snapshot-export",
    title: "Snapshot Export",
    description: "Export global, host-scoped, or combined portal data snapshots.",
    route: "/app/migration/export",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["snapshot", "export", "migration", "host", "global", "both"],
    entities: ["snapshot"],
  },
  {
    id: "snapshot-convert",
    title: "Snapshot Convert",
    description: "Convert exported snapshot data for another host.",
    route: "/app/migration/convert",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["snapshot", "convert", "migration", "host"],
    entities: ["snapshot"],
  },
  {
    id: "user-host",
    title: "User Host",
    description: "Manage host membership for the current user.",
    route: "/app/userHost",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["host", "user", "membership"],
    entities: ["host", "user"],
  },
  {
    id: "account-profile",
    title: "My Profile",
    description: "Review and update the current user's profile.",
    route: "/app/profile",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["profile", "account", "user"],
    entities: ["userId"],
  },
  {
    id: "account-payment",
    title: "My Payment",
    description: "Review and update the current user's payment settings.",
    route: "/app/payment",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["payment", "account", "billing"],
    entities: ["userId"],
  },
  {
    id: "account-messages",
    title: "Private Messages",
    description: "Review and reply to private messages.",
    route: "/app/messages",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["message", "mail", "private"],
    entities: ["userId"],
  },
  {
    id: "account-orders",
    title: "My Orders",
    description: "Review user order activity.",
    route: "/app/userOrders",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["orders", "account", "merchant"],
    entities: ["userId"],
  },
  {
    id: "host-admin",
    title: "Host Admin",
    description: "Create and manage host records.",
    route: "/app/host/HostAdmin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["host", "tenant", "admin", "membership"],
    entities: ["host"],
  },
  {
    id: "host-user-admin",
    title: "Host Users",
    description: "Assign users to a selected host and manage host membership.",
    route: "/app/host/hostUser",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["host", "user", "membership", "assign"],
    entities: ["host", "user"],
  },
  {
    id: "user-admin",
    title: "User Admin",
    description: "Onboard and manage users for the current host.",
    route: "/app/user",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["user", "admin", "onboard", "membership"],
    entities: ["user", "host"],
  },
  {
    id: "ref-table-admin",
    title: "Reference Table Admin",
    description: "Create and manage reference-data tables.",
    route: "/app/ref/tableAdmin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "table", "admin"],
    entities: ["table"],
    helpPath: "/help/portal-view/pages/ref-table-admin",
  },
  {
    id: "ref-value",
    title: "Reference Values",
    description: "Create and manage values for reference-data tables.",
    route: "/app/ref/value",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "value", "code"],
    entities: ["table", "value"],
  },
  {
    id: "ref-locale",
    title: "Reference Locales",
    description: "Create and manage localized labels for reference values.",
    route: "/app/ref/locale",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "locale", "language", "label"],
    entities: ["value", "language"],
  },
  {
    id: "ref-relation-type",
    title: "Reference Relation Types",
    description: "Create and manage reference-data relation types.",
    route: "/app/ref/relationTypeAdmin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "relation", "type"],
    entities: ["relation"],
  },
  {
    id: "ref-relation",
    title: "Reference Relations",
    description: "Create and manage relationships between reference values.",
    route: "/app/ref/relation",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "relation", "value"],
    entities: ["relation", "value"],
  },
  {
    id: "genai-agent-definition",
    title: "GenAI Agent Definitions",
    description: "Create and manage GenAI agent definitions and model settings.",
    route: "/app/genai/AgentDefinition",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "agent", "definition", "model"],
    entities: ["agentDefId", "host"],
  },
  {
    id: "genai-skill",
    title: "GenAI Skills",
    description: "Create and manage reusable GenAI skills.",
    route: "/app/genai/Skill",
    category: "Portal Administration",
    roles: ["admin"],
    helpPath: "/help/portal-view/pages/skill-workspace",
    keywords: ["genai", "skill", "prompt", "content"],
    entities: ["skillId", "parentSkillId"],
  },
  {
    id: "genai-skill-workspace",
    title: "GenAI Skill Workspace",
    description: "Review a skill, link tools and workflows, preview content, and test the primary workflow.",
    route: "/app/genai/SkillWorkspace",
    category: "Portal Administration",
    roles: ["admin"],
    helpPath: "/help/portal-view/pages/skill-workspace",
    keywords: ["genai", "skill", "workspace", "tool", "workflow", "preview", "test"],
    entities: ["skillId", "parentSkillId", "toolId", "wfDefId"],
  },
  {
    id: "genai-tool",
    title: "GenAI Tools",
    description: "Create and manage GenAI tool definitions.",
    route: "/app/genai/Tool",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "tool", "mcp", "implementation"],
    entities: ["toolId"],
  },
  {
    id: "genai-agent-skill",
    title: "GenAI Agent Skills",
    description: "Link skills to agent definitions.",
    route: "/app/genai/AgentSkill",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "agent", "skill", "link"],
    entities: ["agentDefId", "skillId"],
  },
  {
    id: "genai-skill-tool",
    title: "GenAI Skill Tools",
    description: "Link tools to GenAI skills.",
    route: "/app/genai/SkillTool",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "skill", "tool", "link"],
    entities: ["skillId", "toolId"],
  },
  {
    id: "genai-tool-param",
    title: "GenAI Tool Parameters",
    description: "Create and manage parameters for GenAI tools.",
    route: "/app/genai/ToolParam",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "tool", "parameter"],
    entities: ["toolId", "paramId"],
  },
  {
    id: "genai-skill-dependency",
    title: "GenAI Skill Dependencies",
    description: "Create and manage dependencies between GenAI skills.",
    route: "/app/genai/SkillDependency",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "skill", "dependency"],
    entities: ["skillId", "dependsOnSkillId"],
  },
  {
    id: "genai-agent-memory",
    title: "GenAI Agent Memory",
    description: "Create and manage memory records for GenAI agents.",
    route: "/app/genai/AgentMemory",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "agent", "memory"],
    entities: ["agentDefId", "memId"],
  },
  {
    id: "genai-session-memory",
    title: "GenAI Session Memory",
    description: "Create and manage session-scoped GenAI memory records.",
    route: "/app/genai/SessionMemory",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "session", "memory"],
    entities: ["sessionId", "agentDefId", "memId"],
  },
  {
    id: "genai-user-memory",
    title: "GenAI User Memory",
    description: "Create and manage user-scoped GenAI memory records.",
    route: "/app/genai/UserMemory",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "user", "memory"],
    entities: ["userId", "agentDefId", "memId"],
  },
  {
    id: "genai-org-memory",
    title: "GenAI Organization Memory",
    description: "Create and manage organization-scoped GenAI memory records.",
    route: "/app/genai/OrgMemory",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "organization", "org", "memory"],
    entities: ["domain", "memId"],
  },
  {
    id: "genai-agent-session-history",
    title: "GenAI Agent Session History",
    description: "Review GenAI session history and tool-call context.",
    route: "/app/genai/AgentSessionHistory",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "agent", "session", "history"],
    entities: ["sessionHistoryId", "processId"],
  },
  {
    id: "oauth-provider",
    title: "OAuth Providers",
    description: "Create and manage OAuth providers and issuer settings.",
    route: "/app/oauth/authProvider",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["oauth", "provider", "issuer", "jwk"],
    entities: ["providerId", "host"],
  },
  {
    id: "oauth-provider-key",
    title: "OAuth Provider Keys",
    description: "Review provider signing and token keys.",
    route: "/app/oauth/providerKey",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["oauth", "provider", "key", "kid", "jwk"],
    entities: ["providerId", "kid"],
  },
  {
    id: "oauth-provider-api",
    title: "OAuth Provider APIs",
    description: "Attach APIs to OAuth providers.",
    route: "/app/oauth/providerApi",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["oauth", "provider", "api", "link"],
    entities: ["providerId", "apiId"],
  },
  {
    id: "oauth-provider-client",
    title: "OAuth Provider Clients",
    description: "Attach OAuth clients to providers.",
    route: "/app/oauth/providerClient",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["oauth", "provider", "client", "link"],
    entities: ["providerId", "clientId"],
  },
  {
    id: "client-app",
    title: "Client Apps",
    description: "Create and manage client applications that own OAuth clients and instance app links.",
    route: "/app/clientApp",
    category: "Portal Administration",
    roles: ["user", "app-admin"],
    helpPath: "/help/portal-view/pages/app-admin",
    keywords: ["client", "app", "oauth", "instance"],
    entities: ["appId", "clientId", "instanceId"],
  },
  {
    id: "oauth-client",
    title: "OAuth Clients",
    description: "Create and manage OAuth clients.",
    route: "/app/oauth/authClient",
    category: "Portal Administration",
    roles: ["user", "oauth-client-admin"],
    helpPath: "/help/portal-view/pages/oauth-client",
    keywords: ["oauth", "client", "app", "token"],
    entities: ["clientId", "apiId", "apiVersionId", "appId", "instanceId"],
  },
  {
    id: "oauth-client-token",
    title: "OAuth Client Tokens",
    description: "Create and revoke client tokens.",
    route: "/app/oauth/clientToken",
    category: "Portal Administration",
    roles: ["user", "oauth-client-admin"],
    helpPath: "/help/portal-view/pages/oauth-client-token",
    keywords: ["oauth", "client", "token", "revoke"],
    entities: ["clientId", "tokenId"],
  },
  {
    id: "user-session",
    title: "User Sessions",
    description: "Review and revoke your OAuth login sessions.",
    route: "/app/user/session",
    category: "Account",
    roles: ["user"],
    helpPath: "/help/portal-view/pages/user-session",
    keywords: ["oauth", "session", "login", "security", "account"],
    entities: ["sessionId", "clientId"],
  },
  {
    id: "user-session-refresh-tokens",
    title: "User Refresh Tokens",
    description: "Review and revoke refresh-token-backed sessions for your account.",
    route: "/app/user/session/refresh-tokens",
    category: "Account",
    roles: ["user"],
    helpPath: "/help/portal-view/pages/user-session",
    keywords: ["oauth", "refresh", "token", "session", "security"],
    entities: ["sessionId", "clientId"],
  },
  {
    id: "user-session-audit",
    title: "User Session Audit",
    description: "Review OAuth login, refresh, and revocation events for your account.",
    route: "/app/user/session/audit",
    category: "Account",
    roles: ["user"],
    helpPath: "/help/portal-view/pages/user-session",
    keywords: ["oauth", "session", "audit", "login", "security"],
    entities: ["sessionId", "clientId"],
  },
  {
    id: "workflow-definition",
    title: "Workflow Definitions",
    description: "Create and manage workflow definitions.",
    route: "/app/workflow/WfDefinition",
    category: "Platform Operations",
    roles: ["user", "workflow-admin"],
    helpPath: "/help/portal-view/pages/workflow-definition",
    keywords: ["workflow", "definition", "namespace"],
    entities: ["wfDefId"],
  },
  {
    id: "workflow-process-info",
    title: "Workflow Process Info",
    description: "Review workflow process instances and status.",
    route: "/app/workflow/ProcessInfo",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["workflow", "process", "instance", "status"],
    entities: ["processId", "wfDefId", "wfInstanceId"],
  },
  {
    id: "workflow-task-info",
    title: "Workflow Task Info",
    description: "Review workflow task state and priority.",
    route: "/app/workflow/TaskInfo",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["workflow", "task", "status", "priority"],
    entities: ["taskId", "processId", "wfTaskId"],
  },
  {
    id: "workflow-task-assignment",
    title: "Workflow Task Assignments",
    description: "Create and manage workflow task assignments.",
    route: "/app/workflow/TaskAsst",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["workflow", "task", "assignment", "assignee"],
    entities: ["taskAsstId", "taskId", "assigneeId"],
  },
  {
    id: "workflow-worklist",
    title: "Workflow Worklists",
    description: "Review assignee worklists by category and status.",
    route: "/app/workflow/Worklist",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["workflow", "worklist", "assignee", "category"],
    entities: ["assigneeId", "categoryId"],
  },
  {
    id: "workflow-audit-log",
    title: "Workflow Audit Logs",
    description: "Review workflow audit events and correlation IDs.",
    route: "/app/workflow/AuditLog",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["workflow", "audit", "log", "correlation"],
    entities: ["auditLogId", "correlationId"],
  },
  {
    id: "schema-admin",
    title: "Schema Admin",
    description: "Create and manage JSON schemas.",
    route: "/app/schema/admin",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["schema", "json", "validation", "admin"],
    entities: ["schemaId", "schemaVersion"],
  },
  {
    id: "rule-admin",
    title: "Rule Admin",
    description: "Create and manage YAML rules, conditions, and actions.",
    route: "/app/rule/admin",
    category: "Platform Operations",
    roles: ["access-admin"],
    helpPath: "/help/portal-view/pages/rule-admin",
    keywords: ["rule", "yaml", "condition", "action"],
    entities: ["ruleId"],
  },
  {
    id: "rule-detail",
    title: "Rule Detail",
    description: "Review rule conditions, actions, raw configuration, and test cases.",
    route: "/app/ruleDetail",
    category: "Platform Operations",
    roles: ["access-admin"],
    keywords: ["rule", "detail", "test case", "condition", "action"],
    entities: ["ruleId", "testId"],
  },
  {
    id: "list-rule",
    title: "List Rule",
    description: "Manage rules configured for service API endpoints.",
    route: "/app/listRule",
    category: "Platform Operations",
    roles: ["access-admin"],
    helpPath: "/help/portal-view/pages/list-rule",
    keywords: ["rule", "endpoint", "api", "action"],
    entities: ["endpointId", "ruleId"],
  },
  {
    id: "config-admin",
    title: "Config Admin",
    description: "Create and manage configuration records and related bindings.",
    route: "/app/config/configAdmin",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "configuration", "property", "instance", "promotion"],
    entities: ["config"],
  },
  {
    id: "config-update",
    title: "Config Update",
    description: "Update inherited and overridden configuration property values for environment, product, product version, and instance-facing scopes.",
    route: "/app/config/update",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "configuration", "property", "override", "environment", "product", "version", "instance", "api", "app"],
    entities: ["config", "propertyId", "environment", "productId", "productVersionId", "instanceId", "instanceApiId", "instanceAppId"],
  },
  {
    id: "config-snapshot",
    title: "Config Snapshots",
    description: "Create and review effective configuration snapshots for selected instances.",
    route: "/app/config/configSnapshot",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "snapshot", "instance", "properties"],
    entities: ["instanceId", "snapshotId"],
  },
  {
    id: "config-snapshot-compare",
    title: "Compare Config Snapshots",
    description: "Compare canonical effective configuration values across two to four snapshots.",
    route: "/app/config/configSnapshotCompare",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "snapshot", "compare", "difference", "values.yml"],
    entities: ["snapshotId"],
  },
  {
    id: "org-admin",
    title: "Organization Admin",
    description: "Create and manage organization records for the current host.",
    route: "/app/org/OrgAdmin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["org", "organization", "metadata"],
    entities: ["domain"],
  },
  {
    id: "category-admin",
    title: "Category Admin",
    description: "Create and manage global or host-scoped entity categories.",
    route: "/app/category/admin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["category", "taxonomy", "metadata"],
    entities: ["categoryId", "entityType"],
  },
  {
    id: "tag-admin",
    title: "Tag Admin",
    description: "Create and manage global or host-scoped entity tags.",
    route: "/app/tag/admin",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["tag", "label", "metadata"],
    entities: ["tagId", "entityType"],
  },
  {
    id: "schedule-admin",
    title: "Schedule Admin",
    description: "Create and manage scheduled portal events and automation triggers.",
    route: "/app/schedule/admin",
    category: "Portal Administration",
    roles: ["user", "schedule-admin"],
    helpPath: "/help/portal-view/pages/schedule-admin",
    keywords: ["schedule", "scheduler", "event", "automation"],
    entities: ["scheduleId"],
  },
  {
    id: "error-admin",
    title: "Error Admin",
    description: "Create and manage portal error-code definitions.",
    route: "/app/error/adminList",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["error", "code", "message", "metadata"],
    entities: ["errorCode"],
  },
  {
    id: "blog-admin",
    title: "Blog Admin",
    description: "Create and manage blog content for the current host.",
    route: "/app/blog/adminList",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["blog", "content", "article"],
    entities: ["blogId"],
  },
  {
    id: "city-map",
    title: "City Map",
    description: "Create or update city map registration data.",
    route: "/app/covid/cityRegistry",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["city", "map", "covid"],
    entities: ["cityId"],
  },
  {
    id: "community-entity",
    title: "Community Entity",
    description: "Create or update the current user's community entity profile.",
    route: "/app/covid/entity",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["community", "entity", "covid", "profile"],
    entities: ["entityType", "userId"],
  },
];

type GeneratedForm = {
  formId?: string;
  helpPath?: string;
  actions?: Array<{
    service?: string;
    action?: string;
    title?: string;
  }>;
  schema?: {
    title?: string;
    required?: string[];
    properties?: Record<string, { title?: string }>;
  };
};

function humanize(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function unique(values: Array<string | undefined>) {
  return Array.from(
    new Set(
      values
        .filter((value): value is string => !!value)
        .flatMap((value) => value.split(/\s+/))
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean),
    ),
  );
}

function formTitle(formId: string, form: GeneratedForm) {
  return form.schema?.title
    ?? form.actions?.[0]?.title
    ?? humanize(formId);
}

function formCategory(form: GeneratedForm) {
  const service = form.actions?.find((action) => action.service)?.service;
  return service ? `${humanize(service)} Forms` : "Generated Forms";
}

export const generatedFormRegistry: PageDefinition[] = Object.entries(forms as Record<string, GeneratedForm>)
  .map(([formId, form]) => {
    const title = formTitle(formId, form);
    const propertyKeys = Object.keys(form.schema?.properties ?? {});
    const propertyTitles = Object.values(form.schema?.properties ?? {}).map((property) => property.title);
    const actionKeywords = form.actions?.flatMap((action) => [
      action.service,
      action.action,
      action.title,
    ]) ?? [];

    return {
      id: `form:${form.formId ?? formId}`,
      title,
      description: `Open ${title}.`,
      route: `/app/form/${form.formId ?? formId}`,
      category: formCategory(form),
      kind: "Form" as const,
      helpPath: form.helpPath,
      keywords: unique([
        formId,
        form.formId,
        title,
        ...(form.schema?.required ?? []),
        ...propertyKeys,
        ...propertyTitles,
        ...actionKeywords,
      ]),
      entities: propertyKeys,
    };
  });

const registeredRoutes = new Set(pageRegistry.map((page) => page.route));

export const allPageRegistry: PageDefinition[] = [
  ...pageRegistry,
  ...generatedFormRegistry.filter((form) => !registeredRoutes.has(form.route)),
];
