import type { TaskDefinition } from "./types";

export const taskRegistry: TaskDefinition[] = [
  {
    id: "mcp-onboard-api",
    title: "Onboard API to MCP Gateway",
    description:
      "Select or create an API, link a version to a gateway, choose MCP tools, and review access control.",
    category: "MCP Gateway",
    roles: ["user"],
    helpPath: "/help/portal-view/tasks/mcp-onboard-api",
    keywords: ["mcp", "gateway", "api", "onboard", "tools", "access"],
    steps: [
      {
        id: "select-api",
        title: "Select or create API",
        description: "Start from an existing API or register a new logical API.",
        route: "/app/mcp/setup?workflow=api",
        required: true,
        keywords: ["api", "create", "select"],
      },
      {
        id: "api-version",
        title: "Select or create API version",
        description: "Choose the API version that will be exposed through MCP.",
        route: "/app/form/createApiVersion",
        required: true,
        dependsOn: ["select-api"],
        keywords: ["version", "api version"],
      },
      {
        id: "deployment-mode",
        title: "Choose deployment mode",
        description: "Decide whether to use a centralized gateway or a distributed sidecar.",
        route: "/app/mcp/setup?workflow=api",
        required: true,
        dependsOn: ["api-version"],
        keywords: ["deployment", "centralized", "distributed"],
      },
      {
        id: "gateway-link",
        title: "Link to gateway or sidecar instance",
        description: "Create or review the instance API link used by MCP Gateway.",
        route: "/app/instance/InstanceApi",
        required: true,
        dependsOn: ["deployment-mode"],
        keywords: ["instance", "gateway", "link"],
      },
      {
        id: "tools",
        title: "Select MCP tools",
        description: "Choose which endpoints or server tools are exposed through MCP.",
        route: "/app/instance/InstanceApiMcpTool",
        required: false,
        dependsOn: ["gateway-link"],
        keywords: ["tools", "mcp", "endpoints"],
      },
      {
        id: "access",
        title: "Configure access control",
        description: "Restrict access by role, group, attribute, or policy where needed.",
        route: "/app/access/rolePermission",
        required: false,
        dependsOn: ["tools"],
        keywords: ["access", "role", "permission", "rbac"],
      },
    ],
  },
  {
    id: "register-standalone-mcp-server",
    title: "Register Standalone MCP Server",
    description:
      "Register an MCP server, define its version and transport, link it to a gateway, and select tools.",
    category: "MCP Gateway",
    roles: ["user"],
    helpPath: "/help/portal-view/tasks/register-standalone-mcp-server",
    keywords: ["mcp", "server", "standalone", "transport", "tools"],
    steps: [
      {
        id: "server",
        title: "Register MCP server",
        description: "Create the logical API record for a standalone MCP server.",
        route: "/app/form/createApi",
        required: true,
        keywords: ["server", "mcp", "api"],
      },
      {
        id: "version",
        title: "Add server version",
        description: "Set the MCP transport and version metadata.",
        route: "/app/form/createApiVersion?apiType=mcp&transportConfig=%7B%22transport%22%3A%22streamable%20http%22%2C%22url%22%3A%22https%3A%2F%2Flightapi.net%2Fmcp%22%7D",
        required: true,
        dependsOn: ["server"],
        keywords: ["version", "transport"],
      },
      {
        id: "gateway",
        title: "Link to gateway",
        description: "Choose the centralized gateway that will proxy the MCP server.",
        route: "/app/instance/InstanceApi",
        required: true,
        dependsOn: ["version"],
        keywords: ["gateway", "instance"],
      },
      {
        id: "tools",
        title: "Review MCP tools",
        description: "Select or review the tools exposed by this MCP server.",
        route: "/app/instance/InstanceApiMcpTool",
        required: false,
        dependsOn: ["gateway"],
        keywords: ["tools"],
      },
    ],
  },
  {
    id: "publish-api",
    title: "Publish API",
    description:
      "Register an API, add a version, and review marketplace visibility before consumers use it.",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/tasks/publish-api",
    keywords: ["api", "publish", "marketplace", "version", "service"],
    steps: [
      {
        id: "create-api",
        title: "Create API",
        description: "Create or update the logical API metadata.",
        route: "/app/form/createApi",
        required: true,
        keywords: ["api", "service", "create"],
      },
      {
        id: "create-version",
        title: "Create API version",
        description: "Add OpenAPI, GraphQL, hybrid, or MCP version information.",
        route: "/app/form/createApiVersion",
        required: true,
        dependsOn: ["create-api"],
        keywords: ["api version", "version"],
      },
      {
        id: "review-marketplace",
        title: "Review marketplace listing",
        description: "Confirm the API appears correctly for consumers.",
        route: "/app/marketplace/api",
        required: false,
        dependsOn: ["create-version"],
        keywords: ["marketplace", "consumer"],
      },
    ],
  },
  {
    id: "register-ai-agent",
    title: "Register AI Agent",
    description:
      "Register an AI agent as an API, create its agent API version, configure the agent profile, and review access or runtime links.",
    category: "API Marketplace",
    roles: ["user"],
    helpPath: "/help/portal-view/tasks/register-ai-agent",
    keywords: ["agent", "ai", "genai", "api", "version", "model", "skill", "access"],
    steps: [
      {
        id: "api",
        title: "Create or select API",
        description: "Create or select the API catalog entry that represents the agent.",
        route: "/app/form/createApi",
        required: true,
        keywords: ["api", "agent", "create"],
      },
      {
        id: "version",
        title: "Create agent API version",
        description: "Create the API version with API type agt.",
        route: "/app/form/createApiVersion?apiType=agt",
        required: true,
        dependsOn: ["api"],
        keywords: ["api version", "agent version", "agt"],
      },
      {
        id: "profile",
        title: "Configure agent profile",
        description: "Create the agent definition using the same identifier as the API version.",
        route: "/app/form/createAgentDefinition",
        required: true,
        dependsOn: ["version"],
        keywords: ["agent definition", "model", "provider"],
      },
      {
        id: "skills",
        title: "Assign skills",
        description: "Attach skills that define the agent's behavior.",
        route: "/app/genai/AgentSkill",
        required: false,
        dependsOn: ["profile"],
        keywords: ["skill", "agent skill"],
      },
      {
        id: "tools",
        title: "Review tools",
        description: "Review tool access through the assigned skills.",
        route: "/app/genai/SkillTool",
        required: false,
        dependsOn: ["skills"],
        keywords: ["tool", "skill tool"],
      },
      {
        id: "access",
        title: "Configure access",
        description: "Review role permissions before the agent is exposed to consumers.",
        route: "/app/access/rolePermission",
        required: false,
        dependsOn: ["profile"],
        keywords: ["access", "permission", "role"],
      },
      {
        id: "runtime",
        title: "Link runtime instance",
        description: "Link the agent API version to a runtime instance when deployment metadata is available.",
        route: "/app/instance/InstanceApi",
        required: false,
        dependsOn: ["profile"],
        keywords: ["runtime", "instance", "deployment"],
      },
    ],
  },
  {
    id: "configure-access-control",
    title: "Configure Access Control",
    description:
      "Create roles and related access assignments before protecting APIs or MCP tools.",
    category: "Access Control",
    roles: ["admin"],
    keywords: ["access", "role", "permission", "group", "attribute", "position"],
    steps: [
      {
        id: "role",
        title: "Create or review role",
        description: "Define the role used by downstream access policies.",
        route: "/app/access/roleAdmin",
        required: true,
        keywords: ["role"],
      },
      {
        id: "group",
        title: "Assign group or user access",
        description: "Connect roles to users, groups, positions, or attributes as needed.",
        route: "/app/access/groupAdmin",
        required: false,
        dependsOn: ["role"],
        keywords: ["group", "user", "position", "attribute"],
      },
      {
        id: "permission",
        title: "Review permissions",
        description: "Confirm the role and permission relationships used by protected actions.",
        route: "/app/access/rolePermission",
        required: false,
        dependsOn: ["role"],
        keywords: ["permission", "role permission"],
      },
    ],
  },
  {
    id: "manage-user-host-access",
    title: "Manage User Host Access",
    description:
      "Create or review a host, onboard a user, assign host membership, and confirm the user's active host.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["host", "user", "membership", "access", "onboard"],
    steps: [
      {
        id: "host",
        title: "Create or review host",
        description: "Confirm the target host exists before assigning users to it.",
        route: "/app/host/HostAdmin",
        required: true,
        keywords: ["host", "tenant"],
      },
      {
        id: "user",
        title: "Onboard or review user",
        description: "Create the user or review an existing user account.",
        route: "/app/user",
        required: true,
        keywords: ["user", "onboard", "account"],
      },
      {
        id: "membership",
        title: "Assign user to host",
        description: "Create or review the user-host membership record.",
        route: "/app/form/createUserHost",
        required: true,
        dependsOn: ["host", "user"],
        keywords: ["user host", "membership", "assign"],
      },
      {
        id: "switch",
        title: "Confirm active host",
        description: "Switch or confirm the current host for the user when needed.",
        route: "/app/userHost",
        required: false,
        dependsOn: ["membership"],
        keywords: ["switch", "current host"],
      },
    ],
  },
  {
    id: "manage-my-account",
    title: "Manage My Account",
    description:
      "Review profile details, payment settings, private messages, orders, and password changes.",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["profile", "payment", "message", "orders", "password", "account"],
    steps: [
      {
        id: "profile",
        title: "Review profile",
        description: "Review and update your user profile.",
        route: "/app/profile",
        required: true,
        keywords: ["profile", "user"],
      },
      {
        id: "payment",
        title: "Review payment settings",
        description: "Review or update saved payment information.",
        route: "/app/payment",
        required: false,
        keywords: ["payment"],
      },
      {
        id: "messages",
        title: "Review private messages",
        description: "Read and reply to private messages.",
        route: "/app/messages",
        required: false,
        keywords: ["message", "mail"],
      },
      {
        id: "orders",
        title: "Review orders",
        description: "Review user or merchant order activity.",
        route: "/app/userOrders",
        required: false,
        keywords: ["order", "merchant"],
      },
      {
        id: "password",
        title: "Change password",
        description: "Change your account password when needed.",
        route: "/app/form/changePasswordForm",
        required: false,
        keywords: ["password", "security"],
      },
    ],
  },
  {
    id: "manage-client-app",
    title: "Manage Client App",
    description:
      "Create or review client applications, OAuth clients, instance app links, and client tokens.",
    category: "Portal Administration",
    roles: ["user", "app-admin", "oauth-client-admin", "instance-admin"],
    helpPath: "/help/portal-view/tasks/manage-client-app",
    keywords: ["client", "app", "oauth", "token", "instance"],
    steps: [
      {
        id: "app",
        title: "Create or review client app",
        description: "Create or select the client application that owns OAuth clients and runtime links.",
        route: "/app/clientApp",
        required: true,
        keywords: ["app", "client"],
      },
      {
        id: "oauth-client",
        title: "Create or review OAuth clients",
        description: "Create or select OAuth clients for the chosen application.",
        route: "/app/oauth/authClient",
        required: false,
        dependsOn: ["app"],
        keywords: ["oauth", "client"],
      },
      {
        id: "instance-app",
        title: "Link app to instance",
        description: "Attach the application to instances when deployment context is required.",
        route: "/app/instance/InstanceApp",
        required: false,
        dependsOn: ["app"],
        keywords: ["instance", "app", "link"],
      },
      {
        id: "token",
        title: "Create or review client tokens",
        description: "Create, review, or revoke tokens for the selected OAuth client.",
        route: "/app/oauth/clientToken",
        required: false,
        dependsOn: ["oauth-client"],
        keywords: ["token", "secret"],
      },
    ],
  },
  {
    id: "manage-portal-metadata",
    title: "Manage Portal Metadata",
    description:
      "Maintain organizations, categories, tags, schedules, and portal error codes.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["metadata", "organization", "category", "tag", "schedule", "error"],
    steps: [
      {
        id: "org",
        title: "Create or review organizations",
        description: "Manage organization records for the current host.",
        route: "/app/org/OrgAdmin",
        required: false,
        keywords: ["org", "organization"],
      },
      {
        id: "category",
        title: "Create or review categories",
        description: "Manage global or host-scoped categories used by portal entities.",
        route: "/app/category/admin",
        required: false,
        keywords: ["category", "taxonomy"],
      },
      {
        id: "tag",
        title: "Create or review tags",
        description: "Manage global or host-scoped tags used to classify portal entities.",
        route: "/app/tag/admin",
        required: false,
        keywords: ["tag", "label"],
      },
      {
        id: "schedule",
        title: "Create or review schedules",
        description: "Manage scheduled portal events and automation triggers.",
        route: "/app/schedule/admin",
        required: false,
        keywords: ["schedule", "event", "automation"],
      },
      {
        id: "error",
        title: "Create or review error codes",
        description: "Manage portal error-code definitions for the current host.",
        route: "/app/error/adminList",
        required: false,
        keywords: ["error", "code", "message"],
      },
    ],
  },
  {
    id: "manage-community-content",
    title: "Manage Community Content",
    description:
      "Maintain blog content, city maps, community entity profiles, and related private-message actions.",
    category: "Portal Administration",
    roles: ["user"],
    keywords: ["blog", "city", "map", "covid", "entity", "message", "community"],
    steps: [
      {
        id: "blog",
        title: "Create or review blogs",
        description: "Create or update blog content for the current host.",
        route: "/app/blog/adminList",
        required: false,
        keywords: ["blog", "content"],
      },
      {
        id: "city-map",
        title: "Create or review city map",
        description: "Create or update city map registration data.",
        route: "/app/covid/cityRegistry",
        required: false,
        keywords: ["city", "map"],
      },
      {
        id: "entity",
        title: "Create or review community entity",
        description: "Create or update the current user's community entity profile.",
        route: "/app/covid/entity",
        required: false,
        keywords: ["entity", "profile"],
      },
      {
        id: "message",
        title: "Send private message",
        description: "Send or reply to private messages related to community content.",
        route: "/app/form/privateMessage",
        required: false,
        keywords: ["message", "private"],
      },
    ],
  },
  {
    id: "manage-configuration",
    title: "Manage Configuration",
    description:
      "Create or review a configuration record, attach scoped properties, and prepare it for promotion.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "configuration", "property", "promotion", "instance"],
    steps: [
      {
        id: "config",
        title: "Create or review config",
        description: "Create the configuration definition or select an existing one.",
        route: "/app/config/configAdmin",
        required: true,
        keywords: ["config", "create"],
      },
      {
        id: "properties",
        title: "Attach config properties",
        description: "Manage base properties, environment overrides, products, instances, and API bindings.",
        route: "/app/config/configProperty",
        required: false,
        dependsOn: ["config"],
        keywords: ["property", "environment", "instance", "product"],
      },
      {
        id: "instance-api",
        title: "Update scoped config values",
        description: "Edit inherited and overridden configuration values for instances, APIs, apps, and app APIs.",
        route: "/app/config/update",
        required: false,
        dependsOn: ["config"],
        keywords: ["instance", "api", "app", "override", "configuration"],
      },
      {
        id: "promote",
        title: "Promote config",
        description: "Export the config for promotion to another host or environment.",
        route: "/app/promotion/export?entityType=config",
        required: false,
        dependsOn: ["config"],
        keywords: ["promotion", "export"],
      },
    ],
  },
  {
    id: "capture-config-snapshot",
    title: "Capture Config Snapshot",
    description:
      "Create or review configuration snapshots for an instance and inspect the captured property views.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["config", "snapshot", "instance", "properties"],
    steps: [
      {
        id: "instance",
        title: "Select instance",
        description: "Select the instance whose effective configuration should be captured.",
        route: "/app/instance/InstanceAdmin",
        required: true,
        keywords: ["instance"],
      },
      {
        id: "snapshot",
        title: "Create or review snapshot",
        description: "Create or select a configuration snapshot for the instance.",
        route: "/app/config/configSnapshot",
        required: true,
        dependsOn: ["instance"],
        keywords: ["snapshot", "config"],
      },
      {
        id: "properties",
        title: "Review captured properties",
        description: "Inspect snapshot properties, files, API bindings, app bindings, products, and environments.",
        route: "/app/config/configSnapshotProperty",
        required: false,
        dependsOn: ["snapshot"],
        keywords: ["properties", "files", "bindings"],
      },
    ],
  },
  {
    id: "manage-deployment",
    title: "Manage Deployment",
    description:
      "Create or review platforms, pipelines, deployment instances, and deployment records.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["deployment", "platform", "pipeline", "instance", "release"],
    steps: [
      {
        id: "platform",
        title: "Create or review platform",
        description: "Confirm the target deployment platform and its client settings.",
        route: "/app/deployment/PlatformAdmin",
        required: true,
        keywords: ["platform", "target"],
      },
      {
        id: "pipeline",
        title: "Create or review pipeline",
        description: "Select the pipeline version used to deploy product or service artifacts.",
        route: "/app/deployment/PipelineAdmin",
        required: true,
        dependsOn: ["platform"],
        keywords: ["pipeline", "version"],
      },
      {
        id: "deployment-instance",
        title: "Create or review deployment instance",
        description: "Map an instance, service, environment, and pipeline for deployment.",
        route: "/app/deployment/instance",
        required: false,
        dependsOn: ["pipeline"],
        keywords: ["instance", "service", "environment"],
      },
      {
        id: "deployment",
        title: "Review deployments",
        description: "Review deployment records and their current execution status.",
        route: "/app/deployment/DeploymentAdmin",
        required: false,
        dependsOn: ["deployment-instance"],
        keywords: ["deployment", "status"],
      },
    ],
  },
  {
    id: "manage-instance",
    title: "Manage Instance",
    description:
      "Create or review instances, runtime endpoints, API links, app links, and path prefixes.",
    category: "Platform Operations",
    roles: ["user", "instance-admin"],
    helpPath: "/help/portal-view/tasks/manage-instance",
    keywords: ["instance", "runtime", "api link", "app link", "path prefix", "gateway"],
    steps: [
      {
        id: "instance",
        title: "Create or review instance",
        description: "Select the logical instance that represents the service runtime or gateway.",
        route: "/app/instance/InstanceAdmin",
        required: true,
        keywords: ["instance", "gateway"],
      },
      {
        id: "runtime",
        title: "Create or review runtime endpoint",
        description: "Register runtime protocol, address, port, environment, and status details.",
        route: "/app/instance/RuntimeInstanceAdmin",
        required: false,
        dependsOn: ["instance"],
        keywords: ["runtime", "endpoint", "port"],
      },
      {
        id: "api-link",
        title: "Link APIs to instance",
        description: "Attach API versions to the instance for gateway routing or service exposure.",
        route: "/app/instance/InstanceApi",
        required: false,
        dependsOn: ["instance"],
        keywords: ["api", "link", "gateway"],
      },
      {
        id: "app-link",
        title: "Link apps to instance",
        description: "Attach application versions to the instance when app deployment context is needed.",
        route: "/app/instance/InstanceApp",
        required: false,
        dependsOn: ["instance"],
        keywords: ["app", "application"],
      },
      {
        id: "app-api-link",
        title: "Link app APIs",
        description: "Connect instance app records to instance API records.",
        route: "/app/instance/InstanceAppApi",
        required: false,
        dependsOn: ["app-link", "api-link"],
        keywords: ["app api", "association"],
      },
      {
        id: "path-prefix",
        title: "Manage path prefixes",
        description: "Configure path prefixes for instance API routing.",
        route: "/app/instance/InstanceApiPathPrefix",
        required: false,
        dependsOn: ["api-link"],
        keywords: ["path", "prefix", "routing"],
      },
    ],
  },
  {
    id: "manage-product-release",
    title: "Manage Product Release",
    description:
      "Create or review product versions, attach environments, pipelines, configs, and scoped properties.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["product", "release", "version", "environment", "pipeline", "config"],
    steps: [
      {
        id: "product-version",
        title: "Create or review product version",
        description: "Create or select the product version being prepared for release.",
        route: "/app/product/ProductAdmin",
        required: true,
        keywords: ["product", "version"],
      },
      {
        id: "environment",
        title: "Attach environments",
        description: "Map the product version to system and runtime environments.",
        route: "/app/product/environment",
        required: false,
        dependsOn: ["product-version"],
        keywords: ["environment", "runtime"],
      },
      {
        id: "pipeline",
        title: "Attach pipelines",
        description: "Attach deployment pipelines to the product version.",
        route: "/app/product/pipeline",
        required: false,
        dependsOn: ["product-version"],
        keywords: ["pipeline"],
      },
      {
        id: "config",
        title: "Attach configs",
        description: "Attach configuration records used by the product version.",
        route: "/app/product/config",
        required: false,
        dependsOn: ["product-version"],
        keywords: ["config"],
      },
      {
        id: "properties",
        title: "Attach config properties",
        description: "Attach individual config properties used by the product version.",
        route: "/app/product/property",
        required: false,
        dependsOn: ["config"],
        keywords: ["property"],
      },
    ],
  },
  {
    id: "promote-configuration",
    title: "Promote Configuration",
    description:
      "Export, import, and review configuration promotion changes across environments.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["promotion", "configuration", "export", "import", "diff"],
    steps: [
      {
        id: "export",
        title: "Export promotion package",
        description: "Create the promotion payload from the source environment.",
        route: "/app/promotion/export",
        required: true,
        keywords: ["export", "promotion"],
      },
      {
        id: "import",
        title: "Import promotion package",
        description: "Apply the promotion payload to the target environment.",
        route: "/app/promotion/import",
        required: true,
        dependsOn: ["export"],
        keywords: ["import", "promotion"],
      },
      {
        id: "history",
        title: "Review promotion history",
        description: "Audit promotion outcomes and compare changes.",
        route: "/app/promotion/history",
        required: false,
        dependsOn: ["import"],
        keywords: ["history", "diff", "audit"],
      },
    ],
  },
  {
    id: "portal-snapshot-migration",
    title: "Export or Convert Portal Snapshot",
    description:
      "Export global, host-scoped, or combined portal data and convert snapshots for target hosts.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["snapshot", "migration", "export", "convert", "host", "global", "both"],
    steps: [
      {
        id: "export",
        title: "Export snapshot",
        description: "Create a global, host-scoped, or combined portal snapshot.",
        route: "/app/migration/export",
        required: true,
        keywords: ["snapshot", "export", "both"],
      },
      {
        id: "convert",
        title: "Convert snapshot",
        description: "Convert a snapshot for a target host when needed.",
        route: "/app/migration/convert",
        required: false,
        dependsOn: ["export"],
        keywords: ["snapshot", "convert"],
      },
    ],
  },
  {
    id: "manage-reference-data",
    title: "Manage Reference Data",
    description:
      "Create or review reference tables, values, localized labels, relation types, and value relations.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["reference", "ref", "table", "value", "locale", "relation"],
    steps: [
      {
        id: "table",
        title: "Create or review reference table",
        description: "Create or select the reference table that owns values.",
        route: "/app/ref/tableAdmin",
        required: true,
        keywords: ["table", "reference"],
      },
      {
        id: "value",
        title: "Manage reference values",
        description: "Create or review values for the selected reference table.",
        route: "/app/ref/value",
        required: false,
        dependsOn: ["table"],
        keywords: ["value", "code"],
      },
      {
        id: "locale",
        title: "Manage localized labels",
        description: "Create or review localized labels for selected reference values.",
        route: "/app/ref/locale",
        required: false,
        dependsOn: ["value"],
        keywords: ["locale", "language", "label"],
      },
      {
        id: "relation-type",
        title: "Create or review relation type",
        description: "Create or select a relation type for value-to-value relationships.",
        route: "/app/ref/relationTypeAdmin",
        required: false,
        keywords: ["relation type", "relationship"],
      },
      {
        id: "relation",
        title: "Manage reference relations",
        description: "Create or review value-to-value relations for the selected relation type.",
        route: "/app/ref/relation",
        required: false,
        dependsOn: ["relation-type"],
        keywords: ["relation", "value relation"],
      },
    ],
  },
  {
    id: "manage-genai-assets",
    title: "Manage GenAI Assets",
    description:
      "Create or review agents, skills, tools, relationships, parameters, memory, and session history.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["genai", "agent", "skill", "tool", "memory", "session"],
    steps: [
      {
        id: "agent",
        title: "Create or review agent definitions",
        description: "Select or create the agent definition that owns skills and memory.",
        route: "/app/genai/AgentDefinition",
        required: true,
        keywords: ["agent", "definition", "model"],
      },
      {
        id: "skill",
        title: "Create or review skills",
        description: "Create or select reusable skills for agents.",
        route: "/app/genai/Skill",
        required: true,
        keywords: ["skill", "prompt", "content"],
      },
      {
        id: "tool",
        title: "Create or review tools",
        description: "Create or select tools that can be exposed to skills and agents.",
        route: "/app/genai/Tool",
        required: true,
        keywords: ["tool", "implementation", "mcp"],
      },
      {
        id: "agent-skill",
        title: "Link agent skills",
        description: "Attach skills to the selected agent definition.",
        route: "/app/genai/AgentSkill",
        required: false,
        dependsOn: ["agent", "skill"],
        keywords: ["agent skill", "link"],
      },
      {
        id: "skill-tool",
        title: "Link skill tools",
        description: "Attach tools to the selected skill.",
        route: "/app/genai/SkillTool",
        required: false,
        dependsOn: ["skill", "tool"],
        keywords: ["skill tool", "link"],
      },
      {
        id: "tool-param",
        title: "Manage tool parameters",
        description: "Create or review parameters for selected tools.",
        route: "/app/genai/ToolParam",
        required: false,
        dependsOn: ["tool"],
        keywords: ["tool", "parameter"],
      },
      {
        id: "memory",
        title: "Manage memory",
        description: "Create or review agent, user, session, and organization memory records.",
        route: "/app/genai/AgentMemory",
        required: false,
        dependsOn: ["agent"],
        keywords: ["memory", "agent", "user", "session", "org"],
      },
      {
        id: "session-history",
        title: "Review session history",
        description: "Review conversation history and tool call records for GenAI sessions.",
        route: "/app/genai/AgentSessionHistory",
        required: false,
        keywords: ["session", "history", "conversation"],
      },
    ],
  },
  {
    id: "manage-oauth-provider",
    title: "Manage OAuth Provider",
    description:
      "Create or review OAuth providers, keys, API links, client links, and issued client tokens.",
    category: "Portal Administration",
    roles: ["admin"],
    keywords: ["oauth", "provider", "client", "token", "key", "api"],
    steps: [
      {
        id: "provider",
        title: "Create or review provider",
        description: "Create or select the OAuth provider used by clients and APIs.",
        route: "/app/oauth/authProvider",
        required: true,
        keywords: ["provider", "issuer", "jwk"],
      },
      {
        id: "keys",
        title: "Review provider keys",
        description: "Review signing and token keys for the selected provider.",
        route: "/app/oauth/providerKey",
        required: false,
        dependsOn: ["provider"],
        keywords: ["key", "kid", "jwk"],
      },
      {
        id: "apis",
        title: "Link provider APIs",
        description: "Attach APIs that use the selected OAuth provider.",
        route: "/app/oauth/providerApi",
        required: false,
        dependsOn: ["provider"],
        keywords: ["api", "link"],
      },
      {
        id: "clients",
        title: "Link provider clients",
        description: "Attach clients that use the selected OAuth provider.",
        route: "/app/oauth/providerClient",
        required: false,
        dependsOn: ["provider"],
        keywords: ["client", "link"],
      },
      {
        id: "client",
        title: "Create or review OAuth clients",
        description: "Create or review OAuth clients for apps, APIs, instances, or service accounts.",
        route: "/app/oauth/authClient",
        required: false,
        keywords: ["client", "application", "service account"],
      },
      {
        id: "tokens",
        title: "Review client tokens",
        description: "Create or revoke client tokens for the selected client.",
        route: "/app/oauth/clientToken",
        required: false,
        dependsOn: ["client"],
        keywords: ["token", "client token", "revoke"],
      },
    ],
  },
  {
    id: "manage-workflow",
    title: "Manage Workflow",
    description:
      "Create or review workflow definitions, start workflow instances, track processes, tasks, assignments, worklists, and audit logs.",
    category: "Platform Operations",
    roles: ["admin"],
    helpPath: "/help/portal-view/tasks/manage-workflow",
    keywords: ["workflow", "process", "task", "assignment", "worklist", "audit"],
    steps: [
      {
        id: "definition",
        title: "Create or review workflow definitions",
        description: "Create or select the workflow definition that drives process instances.",
        route: "/app/workflow/WfDefinition",
        required: true,
        keywords: ["workflow", "definition", "namespace"],
      },
      {
        id: "start",
        title: "Start workflow",
        description: "Start a new workflow instance from the selected definition.",
        route: "/app/form/startWorkflow",
        required: false,
        dependsOn: ["definition"],
        keywords: ["start", "instance"],
      },
      {
        id: "process",
        title: "Review process instances",
        description: "Review process state, status, subtype, and trigger details.",
        route: "/app/workflow/ProcessInfo",
        required: false,
        dependsOn: ["definition"],
        keywords: ["process", "instance", "status"],
      },
      {
        id: "task",
        title: "Review workflow tasks",
        description: "Review tasks created by workflow process instances.",
        route: "/app/workflow/TaskInfo",
        required: false,
        dependsOn: ["process"],
        keywords: ["task", "status", "priority"],
      },
      {
        id: "assignment",
        title: "Manage task assignments",
        description: "Review or create assignments for workflow tasks.",
        route: "/app/workflow/TaskAsst",
        required: false,
        dependsOn: ["task"],
        keywords: ["assignment", "assignee"],
      },
      {
        id: "worklist",
        title: "Review worklists",
        description: "Review assignee worklists by category and status.",
        route: "/app/workflow/Worklist",
        required: false,
        dependsOn: ["assignment"],
        keywords: ["worklist", "assignee", "category"],
      },
      {
        id: "audit",
        title: "Review workflow audit logs",
        description: "Review audit events and correlation details for workflow activity.",
        route: "/app/workflow/AuditLog",
        required: false,
        keywords: ["audit", "correlation", "log"],
      },
    ],
  },
  {
    id: "manage-schema-rules",
    title: "Manage Schemas and Rules",
    description:
      "Create or review JSON schemas, YAML rules, and executable rule test cases.",
    category: "Platform Operations",
    roles: ["admin"],
    keywords: ["schema", "json schema", "rule", "yaml rule", "test case"],
    steps: [
      {
        id: "schema",
        title: "Create or review JSON schemas",
        description: "Create or select schemas used by portal configuration and validation flows.",
        route: "/app/schema/admin",
        required: false,
        keywords: ["schema", "json", "validation"],
      },
      {
        id: "rule",
        title: "Create or review rules",
        description: "Create or select rules and review their conditions and actions.",
        route: "/app/rule/admin",
        required: true,
        keywords: ["rule", "condition", "action"],
      },
      {
        id: "detail",
        title: "Review rule detail",
        description: "Inspect rule conditions, actions, raw configuration, and test cases.",
        route: "/app/ruleDetail",
        required: false,
        dependsOn: ["rule"],
        keywords: ["rule detail", "conditions", "actions"],
      },
      {
        id: "test-case",
        title: "Create rule test case",
        description: "Add executable test cases for a selected rule.",
        route: "/app/form/createRuleTestCase",
        required: false,
        dependsOn: ["rule"],
        keywords: ["test", "test case", "executor"],
      },
    ],
  },
];
